name: simple-inventory-build

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NodeJS environment setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install NestJS CLI
        run: npm install -g @nestjs/cli

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build
